---
- name: create service dir
  file:
    path: "/etc/systemd/system/sphinxsearch.service.d"
    state: directory
    mode: 0755

- name: place override.conf
  template:
    src: systemd-override.j2
    dest: "/etc/systemd/system/sphinxsearch.service.d/override.conf"
    owner: root
    group: root
    mode: 0644
  notify: reload sphinxsearch unit

- name: create directory {{ sphinxsearch_templates_dir }}/sphinxsearch
  file:
    path: "{{ sphinxsearch_templates_dir }}/sphinxsearch"
    state: directory
    owner: "root"
    group: "root"

- name: place inital-setup script
  template:
    src: initial-setup.j2
    dest: "{{ sphinxsearch_templates_dir }}/sphinxsearch/initial-setup"
    owner: "root"
    group: "root"
    mode: 0750
