---
- name: gather required facts
  setup:
    gather_subset: [min]
  when: ansible_distribution_release is not defined

- name: install
  include_tasks: install.yml
  when: sphinxsearch_setup == "full" or sphinxsearch_setup == "install"

- name: prepare initial-setup script
  include_tasks: initial-setup.yml
  when: spinxsearch_initial_setup

- name: configure
  import_tasks: configure.yml
  when: sphinxsearch_setup == "full" or sphinxsearch_setup == "configure"
